### ISSUE TITLE
GD-104: Inner exception handling is inconsistent between sync and async methods

### ISSUE THREAD

**Issue by sbergen** [MikeSchulze/gdUnit4Net#106]
### The used API version

4.2.3 (Latest Release)

### The used Godot version

v4.2.2.stable.mono.official [15073afe3]

### Operating System

Windows 11

### Describe the bug

When a test method is `async` and the exception causing a test failure has a non-null `InnerException`, the inner exception gets reported as the failure reason. This is unexpected, and inconsistent with synchronous test methods.

This behavior is particularly problematic when used with other testing utilities, which might wrap the "user exception" with contextual information ([example](https://github.com/sbergen/Responsible/blob/main/com.beatwaves.responsible/Runtime/TestFailureException.cs)).

### Steps to Reproduce

Example:
1. Add the following tests:
   ```cs
   [TestCase]
   public async Task Async()
   {
       throw new Exception("outer", new Exception("inner"));
   }

   [TestCase]
   public void Sync()
   {
       throw new Exception("outer", new Exception("inner"));
   }
   ```

2. Run the tests.
3. Check the failure output

**Expected:** Both failures have "outer" as the reason.
**Actual:** The async test has "inner" as the reason.

**Comment by MikeSchulze** [comment]
Thanks for the report, I'll take a look tomorrow.
