### ISSUE TITLE
GD-XXX: Running a single test case runs all of them

### ISSUE THREAD

**Issue by DrMouseInc** [MikeSchulze/gdUnit4Net#107]
### The used Test Adapter version

1.1.1

### The used Godot version

v4.2.2.stable.mono.official [15073afe3]

### Operating System

Windows 11

### Describe the bug

Running a single TestCase for a test method from the Visual Studio Test explorer window runs all the test cases, at least in Debug mode.

### Steps to Reproduce

1. Creata a test like described below
2. Set a breakpoint inside the test method on the assertion
3. Use the Visual Studio Test Explorer window and right click on a single test case, select Debug from the dropdown

The test will be run for each TestCase attribute and the breakpoint hit, with value going through 0, 1, 2

```c#
namespace Examples;

using GdUnit4;

[TestSuite]
public class TestClass1 {
	[TestCase(0)]
	[TestCase(1)]
	[TestCase(2)]
	public void Test1(int value) {
		Assertions.AssertInt(value).IsEqual(7);
	}
}
```

**Comment by MikeSchulze** [comment]
this is related to #27
