### ISSUE TITLE
GD-143: Rider test debugging doesn't work

### ISSUE THREAD

**Issue by JustASquid** [MikeSchulze/gdUnit4Net#143]
### The used GdUnit4 version

4.4.1 (Pre Release/Master branch)

### The used Godot version

v4.3

### Operating System

Windows

### Describe the bug

I've followed all the steps in the documentation to setup integration with Rider. Using Rider 2024.2.7.

On rider start, I see that it has picked up the unit tests:

![image](https://github.com/user-attachments/assets/44ee7ae8-61da-492a-9de5-782dafd17b10)

Running the test in Rider works as expected - the project application is launched, the test runs and then the project application closes.

However, debugging the test doesn't work. The test doesn't succeed or fail, instead nothing happens. Afterwards, Rider loses track of the test altogether:

![image](https://github.com/user-attachments/assets/54ac35fa-60eb-49b9-9107-b905383b87b3)

Running `dotnet test` directly works fine and runs all the tests.

Could I be missing something?

### Steps to Reproduce

Example:
1. Open the application.
2. Click on '...' button.
3. Enter '...' in the input field.
4. Click on 'Submit'.
5. Observe the error in the console.

If the issue involves code, please include relevant snippets below:

```gd
# Sample code demonstrating the issue
func reproduce_issue():
    # Your code here
    pass
```

**Comment by MikeSchulze** [comment]
Hi, can you please add the missing information.
- the system: ?
- the used GdUnit4 API version: ?
- the used GdUnit4 test adapter version: ?
- rider version : 2024.2.7.
And please add the test execution log

**Comment by JustASquid** [comment]
Sorry @MikeSchulze 

System: Windows 10
Package versions:

```
    <PackageReference Include="gdUnit4.api" Version="4.4.*" />
    <PackageReference Include="gdUnit4.test.adapter" Version="2.*" />
```

Where can I find the test execution log? I don't see how that's useful anyway if the problem is "Rider doesn't pick up the tests"

**Comment by MikeSchulze** [comment]
> Where can I find the test execution log? I don't see how that's useful anyway if the problem is "Rider doesn't pick up the tests"

![image](https://github.com/user-attachments/assets/b8a79b71-d407-4858-83c0-6670a9c8e6d8)


Check your project is configured correctly, do not use release candidates, there is no guaranty of all works.

https://mikeschulze.github.io/gdUnit4/csharp_project_setup/vstest-adapter/#install-nuget-packages-and-project-references

Here the actual suggested project configuration:
```
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>11.0</LangVersion>
    <!--Force nullable warnings, you can disable if you want-->
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!--Disable warning of invalid/incompatible GodotSharp version-->
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <!--Required for GdUnit4-->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="gdUnit4.api" Version="4.3.*" />
    <PackageReference Include="gdUnit4.test.adapter" Version="2.*" />
  </ItemGroup>
  ```

Have you setup the `.runsettings` ?
https://mikeschulze.github.io/gdUnit4/csharp_project_setup/vstest-adapter/#preconditions

**Comment by MikeSchulze** [comment]
Hi @JustASquid any update?

**Comment by MikeSchulze** [comment]
Closed, I am not able to reproduce it and the reporter no longer responds
