### ISSUE TITLE
GD-78: Add Support for `.Net GDExtension` point

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4Net#78]
**Is your feature request related to a problem? Please describe.**
With [Godot.Bindings](https://github.com/raulsntos/godot-dotnet/tree/master/src/Godot.Bindings) we are able to provide `gdunit4.api` as a Godot extension point.

**Describe the solution you'd like**
Use the new project [godot-dotnet](https://github.com/raulsntos/godot-dotnet) to build an `GDExtension`.
This will allow us to use the api direct in Godot.

**Describe alternatives you've considered**
The alternative is actually to load the code as `CSharpScript` and build an GDScript bridge to access the C# API.

**Additional context**

**Comment by GeorgeS2019** [comment]
@MikeSchulze 

It is now possible to  use libgodot.dll for > Godot 4.3.x for windows using c#. This would mean this feature request is needed to improve the **reliability** of using **c# bindings for GDExtension**
https://github.com/JiepengTan/libgodot_llgo_demo/issues/4#issue-2472109625

We encounter the challenges that the existing [godot-dotnet](https://github.com/raulsntos/godot-dotnet) is not up-to-date for the latest godot > 4.3.x

We many need **community effort** to have a good test coverage of the c# bindings exposed by the GDExtension

**Comment by MikeSchulze** [comment]
Closed it for now, we can reopen if the Godot finally available as a lib.

**Comment by GeorgeS2019** [comment]
https://github.com/migeran/libgodot_project/issues/1#issuecomment-2294996680

@MikeSchulze 

Pending libgodot
Pending Godot dotnet missing features
