### ISSUE TITLE
GD-86: Space in folder name prevents tests from running

### ISSUE THREAD

**Issue by DrMouseInc** [MikeSchulze/gdUnit4Net#86]
### The used Test Adapter version

1.2.0 (Pre Release/Master branch)

### The used Godot version

v4.2.1.stable.mono.official [b09f793f5]

### Operating System

Windows 11

### Describe the bug

I expected the test runner to run the tests regardless of the folder path and give me results back. Instead the runner fails to run any tests and just opens the Godot editor with a modal window on top that is shown below

![image](https://github.com/MikeSchulze/gdUnit4Net/assets/167206053/597e65aa-92cb-4dfb-8224-9fb52ff9f99a)

### Steps to Reproduce

Download this repo to a folder path with no spaces in it, I downloaded it to C:\Temp\gdUnit4Net-master. Open the example scene in the Godot editor (I believe this was required?), then build the whole solution either from the command line or IDE. Add the GODOT_BIN to the .runsettings file and run the tests from commandline or IDE. Example shown below

> PS C:\Temp\gdUnit4Net-master\example> dotnet test -s .\.runsettings
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   exampleProject -> C:\Temp\gdUnit4Net-master\example\.godot\mono\temp\bin\Debug\exampleProject.dll
> Test run for C:\Temp\gdUnit4Net-master\example\.godot\mono\temp\bin\Debug\exampleProject.dll (.NETCoreApp,Version=v8.0)
> Microsoft (R) Test Execution Command Line Tool Version 17.9.0 (x64)
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
>   Failed failed [12 ms]
>   Error Message:
>    Expecting: 'True' but is 'False'
>   Stack Trace:
>      at Examples.ExampleTest.failed() in C:\Temp\gdUnit4Net-master\example\test\ExampleTest.cs:line 19
> 
> Html test results file : C:\Temp\gdUnit4Net-master\example\TestResults\test-result.html
> WARNING: Overwriting results file: C:\Temp\gdUnit4Net-master\example\TestResults\test-result.trx
> Results File: C:\Temp\gdUnit4Net-master\example\TestResults\test-result.trx
> 
> Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration: 15 ms - exampleProject.dll (net8.0)

Change the folder path to contain a space and the test run fails with the modal window shown previously

> PS C:\Temp\gdUnit4Net-master space\example> dotnet test -s .\.runsettings
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   exampleProject -> C:\Temp\gdUnit4Net-master space\example\.godot\mono\temp\bin\Debug\exampleProject.dll
> Test run for C:\Temp\gdUnit4Net-master space\example\.godot\mono\temp\bin\Debug\exampleProject.dll (.NETCoreApp,Version=v8.0)
> Microsoft (R) Test Execution Command Line Tool Version 17.9.0 (x64)
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> No test is available in C:\Temp\gdUnit4Net-master space\example\.godot\mono\temp\bin\Debug\exampleProject.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> Html test results file : C:\Temp\gdUnit4Net-master space\example\TestResults\test-result.html
> WARNING: Overwriting results file: C:\Temp\gdUnit4Net-master space\example\TestResults\test-result.trx
> Results File: C:\Temp\gdUnit4Net-master space\example\TestResults\test-result.trx

**Comment by MikeSchulze** [comment]
Thanks for reporting, I will take tomorrow a look what goes wrong here.
