### ISSUE TITLE
GD-91: `SceneRunner.SimulateFrames`  doesn't propagate exceptions

### ISSUE THREAD

**Issue by DrMouseInc** [MikeSchulze/gdUnit4Net#91]
### The used Test API version

4.2.3

### The used Godot version

v4.2.2.stable.mono.official [15073afe3]

### Operating System

Windows 11

### Describe the bug

Loading a scene with ISceneRunner.Load and letting it run a little while with SimulateFrames doesn't propagate any possible exceptions so they can be asserted against in the test

### Steps to Reproduce

Have any simple scene and attach the following script to any node

```
using Godot;
using System;

namespace GdUnitSetup;

public partial class Exceptor : Node {
	public override void _Process(double delta) {
		SeeIfBedtime((int)Time.GetTicksMsec());
	}

	public void SeeIfBedtime(int ticks) {
		if (ticks > 200) {
			throw new ArgumentException("Past my bedtime");
		}
	}
}
```

Then have a test class like 

```
using GdUnit4;
using GdUnit4.Asserts;
using System.Threading.Tasks;

namespace GdUnitSetup.Tests;

[TestSuite]
public class ExceptionTest {
	[TestCase]
	public async Task Test1() {
		ISceneRunner runner = ISceneRunner.Load("res://Scenes/Scene1.tscn");

		IExceptionAssert exceptionAssert = await Assertions.AssertThrown(runner.SimulateFrames(100));
		//IExceptionAssert exceptionAssert = await Assertions.AssertThrown(runner.InvokeAsync("SeeIfBedtime", 500));

		Assertions.AssertObject(exceptionAssert).IsNotNull();
	}
}
```

Running the scene from the editor or running the tests in debug mode from Visual Studio will print the exceptions to console so they are thrown. But the test will always fail as the exceptionAssert will always be null. I found #22 from which the commented out line is from. If that is swapped to be running, then the test will pass.

Please advice if I'm trying to assert the SimulateFrames exceptions wrong somehow, I just think it would be exceedingly useful to be able to assert that no exceptions or a specific exception were thrown during the running of a scene

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

**Comment by MikeSchulze** [comment]
# Update
There is actual no way to propagate exceptions thrown inside the main loop, the engine itself is catching this and do only propagate this be logging.
See:
* https://github.com/godotengine/godot/issues/28259
* https://github.com/godotengine/godot-proposals/issues/297

My hands are currently tied, and I can't do anything without an engine provided exception handler.

**Comment by DrMouseInc** [comment]
Sad to see this, I hope you can add it if Godot ever adds a hook for it
