### ISSUE TITLE
GD-96: Methods with a single parameterized test case are not executed

### ISSUE THREAD

**Issue by DrMouseInc** [MikeSchulze/gdUnit4Net#96]
### The used Test Adapter version

1.1.1

### The used Godot version

v4.2.2.stable.mono.official [15073afe3]

### Operating System

Windows 11

### Describe the bug

I was starting to add parameters for my test method and added the first TestCase. Running the tests I expected all the tests, including the one with a single TestCase to be run. But, that test is not run and VS's Output window shows this in the Tests dropdown:

> Building Test Projects
> ========== Starting test run ==========
> Start executing tests, 1 TestCases total.
> Current directory set to: C:\Users\User\Documents\Godot Projects\Conveyorer
> Run with args  --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="C:\Users\User\Documents\Godot Projects\Conveyorer\GdUnitRunner_5b0e82a4-759e-42e2-9e8d-e96eeeb2b2c0.cfg" 
> stdout: Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
> stdout: Vulkan API 1.3.262 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6600M
> stdout: Load testsuite C:\Users\User\Documents\Godot Projects\Conveyorer\UnitTests\SingleNodeTests.cs
> stdout: Testrun ends with exit code: 100, FailFast:False
> Godot ends with exit code: 100
> Run TestRunner ends with 100
> ========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 975 ms ==========
> 

### Steps to Reproduce

Have a working test setup. Add the test below and confirm it runs correctly for both parameters

```
[TestCase(true)]
[TestCase(false)]
public void ParametrisedTest(bool value) {
	Assertions.AssertBool(value).IsTrue();
}
```

Then comment out either TestCase attribute, compile, rerun tests. The test method is not run.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.
